AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Checkmate Replay Hub - Milestones 2, 3 and 4

Parameters:
  SesFromEmail:
    Type: String

  PublicUrl:
    Type: String

Globals:
  Function:
    Runtime: python3.12
    Timeout: 60
    MemorySize: 256

  HttpApi:
    CorsConfiguration:
      AllowOrigins:
        - "http://100.54.111.76"
        - "http://localhost"
      AllowHeaders:
        - "content-type"
        - "authorization"
      AllowMethods:
        - "POST"
        - "GET"
        - "OPTIONS"

Resources:

  SubmissionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  SubmissionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub CheckmateSubmissions-${AWS::StackName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: submissionId
          AttributeType: S
      KeySchema:
        - AttributeName: submissionId
          KeyType: HASH

  ProcessingDeadLetterQueue:
    Type: AWS::SQS::Queue

  ProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessingDeadLetterQueue.Arn
        maxReceiveCount: 3

  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/upload/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SubmissionTable
          BUCKET_NAME: !Ref SubmissionBucket
          SES_FROM_EMAIL: !Ref SesFromEmail
          PUBLIC_URL: !Ref PublicUrl

      Policies:
        - S3CrudPolicy:
            BucketName: !Ref SubmissionBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref SubmissionTable
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"

      Events:
        Upload:
          Type: HttpApi
          Properties:
            Path: /upload
            Method: POST

        GetSubmissionStatus:
          Type: HttpApi
          Properties:
            Path: /submissions/{submissionId}
            Method: GET

  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/processor/
      Handler: app.lambda_handler
      Timeout: 60
      MemorySize: 512

      Environment:
        Variables:
          TABLE_NAME: !Ref SubmissionTable
          PROCESSING_QUEUE_URL: !Ref ProcessingQueue
          BUCKET_NAME: !Ref SubmissionBucket
          SES_FROM_EMAIL: !Ref SesFromEmail

      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SubmissionBucket

        - DynamoDBCrudPolicy:
            TableName: !Ref SubmissionTable

        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"

        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt ProcessingQueue.Arn

      Events:
        Queue:
          Type: SQS
          Properties:
            Queue: !GetAtt ProcessingQueue.Arn
            BatchSize: 1

  QueueSendPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CheckmateUploadSendToQueue

      Roles:
        - !Ref UploadFunctionRole

      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt ProcessingQueue.Arn

Outputs:

  BucketName:
    Description: Submission S3 bucket
    Value: !Ref SubmissionBucket

  TableName:
    Description: DynamoDB table
    Value: !Ref SubmissionTable

  QueueUrl:
    Description: Processing queue URL
    Value: !Ref ProcessingQueue

  ProcessingQueueArn:
    Description: Processing queue ARN
    Value: !GetAtt ProcessingQueue.Arn

  ProcessorFunctionName:
    Description: Chess processor Lambda function name
    Value: !Ref ProcessorFunction
